import { iPlayers } from "./interfaces";

export const players: iPlayers[] = [
  {
    dorsal: 1,
    name: "Franco Armani",
    imgAns: "/assets/champions-photos/answer/1-franco-armani.jpg",
    //"https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/1-franco-armani.jpg?alt=media&token=7b8143d0-f15c-49d6-8045-609395d4ba83",
    imgQuest: "/assets/champions-photos/guess/1-franco-armani.jpg",
  },
  {
    dorsal: 2,
    name: "Juan Foyth",
    imgAns: "/assets/champions-photos/answer/2-juan-foyth.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/2-juan-foyth.jpg?alt=media&token=31bcb30e-aa21-464a-a3e7-112a41ec3ed2",
    imgQuest: "/assets/champions-photos/guess/2-juan-foyth.jpg",
  },
  {
    dorsal: 3,
    name: "Nicolas Tagliafico",
    imgAns: "/assets/champions-photos/answer/3-nicolas-tagliafico.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/3-nicolas-tagliafico.jpg?alt=media&token=1f299ef1-cb6a-4f22-a4fb-f9352e16cdc0",
    imgQuest: "/assets/champions-photos/guess/3-nicolas-tagliafico.jpg",
  },
  {
    dorsal: 4,
    name: "Gonzalo Montiel",
    imgAns: "/assets/champions-photos/answer/4-gonzalo-montiel.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/4-gonzalo-montiel.jpg?alt=media&token=9e0f48a0-06b7-4f38-8214-8f277049f647",
    imgQuest: "/assets/champions-photos/guess/4-gonzalo-montiel.jpg",
  },
  {
    dorsal: 5,
    name: "Leandro Paredes",
    imgAns: "/assets/champions-photos/answer/5-leandro-paredes.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/5-leandro-paredes.jpg?alt=media&token=4c76fbe0-05ae-40cb-a10c-9f4700b5a235",
    imgQuest: "/assets/champions-photos/guess/5-leandro-paredes.jpg",
  },
  {
    dorsal: 6,
    name: "German Pezzella",
    imgAns: "/assets/champions-photos/answer/6-german-pezzella.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/6-german-pezzella.jpg?alt=media&token=ea00a838-0259-4cd3-b447-669e51a4a987",
    imgQuest: "/assets/champions-photos/guess/6-german-pezzella.jpg",
  },
  {
    dorsal: 7,
    name: "Rodrigo De Paul",
    imgAns: "/assets/champions-photos/answer/7-rodrigo-de-paul.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/7-rodrigo-de-paul.jpg?alt=media&token=bb64add9-b20a-4b9a-a756-7ac79b4b188e",
    imgQuest: "/assets/champions-photos/answer/7-rodrigo-de-paul.jpg",
  },
  {
    dorsal: 8,
    name: "Huevo Acuña",
    imgAns: "/assets/champions-photos/answer/8-marcos-acuna.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/8-marcos-acuna.jpg?alt=media&token=fbb33aff-9f67-4388-975d-872c4e7e1a3e",
    imgQuest: "/assets/champions-photos/guess/8-marcos-acuna.jpg",
  },
  {
    dorsal: 9,
    name: "Julian Alvarez",
    imgAns: "/assets/champions-photos/answer/9-julian-alvarez.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/9-julian-alvarez.jpg?alt=media&token=d02585d2-b8b9-4e33-9dd6-447679c1f151",
    imgQuest: "/assets/champions-photos/guess/9-julian-alvarez.jpg",
  },
  {
    dorsal: 10,
    name: "Lionel Messi",

    imgAns: "/assets/champions-photos/answer/10-dios.jpg",
    // "https://firebasestorage.googleapis.com/v0/b/guess-your-champion.appspot.com/o/10-dios.jpg?alt=media&token=83d02942-2eb8-4352-9101-0a51315eddca",
    imgQuest: "/assets/champions-photos/guess/10-dios.jpg",
  },
  {
    dorsal: 11,
    name: "Angel Di María",
    imgQuest: "/assets/champions-photos/guess/11-angel-di-maria.jpg",
    imgAns: "/assets/champions-photos/answer/11-angel-di-maria-full.jpg",
  },
  {
    dorsal: 12,
    name: "Geronimo Rulli",
    imgQuest: "/assets/champions-photos/guess/12-geronimo-rulli.jpg",
    imgAns: "/assets/champions-photos/answer/12-geronimo-rulli-full.jpg",
  },
  {
    dorsal: 13,
    name: "Cristian Romero",
    imgQuest: "/assets/champions-photos/guess/13-cuti-romero.jpg",
    imgAns: "/assets/champions-photos/answer/13-cuti-romero-full.jpg",
  },
  {
    dorsal: 14,
    name: "Exequiel Palacios",
    imgQuest: "/assets/champions-photos/guess/14-exequiel-palacios.jpg",
    imgAns: "/assets/champions-photos/answer/14-exequiel-palacios-full.jpg",
  },
  {
    dorsal: 15,
    name: "Angel Correa",
    imgQuest: "/assets/champions-photos/guess/15-angel-correa.jpg",
    imgAns: "/assets/champions-photos/answer/15-angel-correa-full.jpg",
  },
  {
    dorsal: 16,
    name: "Thiago Almada",
    imgQuest: "/assets/champions-photos/guess/16-thiago-almada.jpg",
    imgAns: "/assets/champions-photos/answer/16-thiago-almada-full.jpg",
  },
  {
    dorsal: 17,
    name: "Papu Gomez",
    imgQuest: "/assets/champions-photos/guess/17-papu-gomez.jpg",
    imgAns: "/assets/champions-photos/answer/17-papu-gomez-full.jpg",
  },
  {
    dorsal: 18,
    name: "Guido Rodriguez",
    imgQuest: "/assets/champions-photos/guess/18-guido-rodriguez.jpg",
    imgAns: "/assets/champions-photos/answer/18-guido-rodriguez-full.jpg",
  },
  {
    dorsal: 19,
    name: "Nicolas Otamendi",
    imgQuest: "/assets/champions-photos/guess/19-nicolas-otamendi.jpg",
    imgAns: "/assets/champions-photos/answer/19-nicolas-otamendi-full.jpg",
  },
  {
    dorsal: 20,
    name: "Alexis MacAllister",
    imgQuest: "/assets/champions-photos/guess/20-alexis-macallister.jpg",
    imgAns: "/assets/champions-photos/answer/20-alexis-macallister-full.jpg",
  },
  {
    dorsal: 21,
    name: "Paulo Dybala",
    imgQuest: "/assets/champions-photos/guess/21-paulo-dybala.jpg",
    imgAns: "/assets/champions-photos/answer/21-paulo-dybala-full.jpg",
  },
  {
    dorsal: 22,
    name: "Lautaro Martinez",
    imgQuest: "/assets/champions-photos/guess/22-lautaro-martinez.jpg",
    imgAns: "/assets/champions-photos/answer/22-lautaro-martinez-full.jpg",
  },
  {
    dorsal: 23,
    name: "Dibu Martinez",
    imgQuest: "/assets/champions-photos/guess/23-dibu-martinez.jpg",
    imgAns: "/assets/champions-photos/answer/23-dibu-martinez-full.jpg",
  },
  {
    dorsal: 24,
    name: "Enzo Fernandez",
    imgQuest: "/assets/champions-photos/guess/24-enzo-fernandez.jpg",
    imgAns: "/assets/champions-photos/answer/24-enzo-fernandez-full.jpg",
  },
  {
    dorsal: 25,
    name: "Lisandro Martinez",
    imgQuest: "/assets/champions-photos/guess/25-lisandro-martinez.jpg",
    imgAns: "/assets/champions-photos/answer/25-lisandro-martinez-full.jpg",
  },
  {
    dorsal: 26,
    name: "Nahuel Molina",
    imgQuest: "/assets/champions-photos/guess/26-nahuel-molina.jpg",
    imgAns: "/assets/champions-photos/answer/26-nahuel-molina-full.jpg",
  },
];
